# Generated by Django 5.2.1 on 2025-05-16 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('item_ingredients', models.TextField()),
                ('item_image_url', models.CharField(max_length=500)),
                ('item_recipie', models.TextField()),
                ('item_cooking_time', models.IntegerField()),
                ('item_cuisine', models.CharField(max_length=200)),
                ('item_author', models.CharField(max_length=200)),
                ('item_video_url', models.CharField(max_length=500)),
                ('item_difficulty', models.CharField(max_length=50)),
                ('item_type', models.CharField(max_length=50)),
            ],
        ),
    ]
