# Generated by Django 5.2.1 on 2025-05-16 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dish', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item_recipie',
            new_name='item_recipe',
        ),
    ]
